name: Build and Test

on:
  #   push:
  #     branches:
  #       - main
  #   pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-platform:
    name: ${{ matrix.os }} / Zig ${{ matrix.zig }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        zig:
          - 0.15.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig }}

      - name: Build
        run: zig build

      - name: Test
        run: zig build test
